### ISSUE TITLE
Incorrect delta output for all paths more than 2 levels deep

### ISSUE THREAD

**Issue by tkurki** [SignalK/signalk-parser-nmea0183#24] opened 2015-02-28 09:28 UTC
See MWV and DBT tests at https://github.com/SignalK/signalk-parser-nmea0183/tree/delta-for-deep-paths/test

**Comment by tkurki** [comment] 2015-02-28 09:30
Path is only two levels deep and the third level is under value:
```
{
  "context": "vessels.85F33882",
  "updates": [
    {
      "source": {
        "timestamp": "2015-02-28T09:29:44.820Z"
      },
      "values": [
        {
          "path": "environment.depth",
          "value": {
            "belowTransducer": {
              "source": {
                "type": "NMEA0183",
                "src": "DBT",
                "label": "signalk-parser-nmea0183"
              },
              "timestamp": "2015-03-28T09:29:44.000Z",
              "value": 10.83
            }
          }
        }
      ]
    }
  ]
}```

**Comment by fabdrol** [comment] 2015-03-20 22:57
The issue is coming from multiplexer. I added the tests for the issue to master, along with some other changes and removed the separate branch. I'm in the process of updating multiplexer to fix this issue. Closing for now, if multiplexer doesn't fix it we can always re-open.

**Comment by tkurki** [comment] 2015-04-22 19:48
As fixing this seems actually pretty simple and doesn't need any Multiplexer changes/rewrite I am reopening.

**Closed** 2015-05-12 15:12 UTC
